version: 0.2
env:
  variables:
      DEBUG: "False"
  #parameter-store:
     # key: "There are no variables"
phases:
  install:
    runtime-versions:
       python: 3.8
#       nodejs: 12
    commands:
#      - ls -alr /var/cache/yum/
      - yum install -y python3-devel mariadb-devel
  pre_build:
    commands:
      - mkdir tmp/pip -p
      - chown root:root -R tmp/
#      - ls -alr tmp/*
      - pip install --cache-dir=tmp/ -r requirements.txt --upgrade
#      - npm install -g lessc
#      - python3 setup.py install
  build:
    commands:
      - python3 manage.py migrate
#      - ENV='Test-V1' DB_NAME='test_v1_connect_1' python3 manage.py migrate
#      - ENV='Test-V1' DB_NAME='test_v1_connect_2' python3 manage.py migrate
#      - ENV='Test-V1' DB_NAME='test_v1_connect_3' python3 manage.py migrate
#      - ENV='Test-V1' DB_NAME='test_v1_connect_4' python3 manage.py migrate
      - python3 manage.py collectstatic -c --noinput
      - python3 manage.py compilemessages -i venv -i public -i requirements.txt -i requirements.txt.py
#      - ENV='Test-V1' python3 manage.py test --keepdb --parallel=4 --failfast --noinput bemosenderrr
  post_build:
    commands:
      - python3 manage.py compile_pyc
      - python3 manage.py clear_cache
      - python3 manage.py invalidate_cachalot
      - find . -type f -name '*.sh' -exec chmod +x {} \;
artifacts:
  files:
    - 'django_iam_dbauth/**/*'
#    - 'flexselect/**/*'
    - 'jet/**/*'
    - 'locale/**/*'
    - 'bemosenderrr/**/*'
    - 'public/**/*'
    - 'Procfile'
    - '*.py'
    - 'requirements.txt'
    - '.ebextensions/**/*'
    - '.platform/**/*'
  discard-paths: false
cache:
  paths:
    - '/root/.cache/**/*'
#    - 'node_modules/**/*'
    - '/var/cache/yum/**/*'
    - 'tmp/**/*'
