bemosenderrr_API_MESSAGE_CODES = {
    1000: "system error",
    1001: "partner id or password incorrect",
    1002: "service name is missing or invalid",
    1003: "version is missing or invalid",
    1004: "unauthorized ip",
    1005: "request format is invalid",
    2000: "successful",
    2101: "order/reference - field is missing or invalid",
    2102: "order/reference - already exists",
    2103: "order/date - field is missing or invalid",
    2104: "order/country - field is missing or invalid",
    2105: "order/currency - field is missing or invalid",
    2200: "payment/code - field is missing or invalid",
    2201: "payment/code - already exists",
    2202: "payment/code - not found",
    2203: "payment/country - field is missing or invalid",
    2204: "payment/currency - field is missing or invalid",
    2205: "payment/amount - field is missing or invalid",
    2206: "payment/delivery - field is missing or invalid",
    2207: "payment/payer - field is missing or invalid",
    2208: "payment/accountnumber - invalid",
    2209: "payment/date - field is missing or invalid",
    2210: "payment/token - field is missing or invalid",
    2211: "payment/token - token is expired",
    2212: "payment/token - not found",
    2213: "payment/code - too many requested",
    2300: "senderr/firstname - field is missing or invalid",
    2301: "senderr/middlename - invalid",
    2302: "senderr/lastname - field is missing or invalid",
    2303: "senderr/address1 - invalid",
    2304: "senderr/address2 - invalid",
    2305: "senderr/city - invalid",
    2306: "senderr/state - invalid",
    2307: "senderr/zipcode - invalid",
    2308: "senderr/country - field is missing or invalid",
    2309: "senderr/phone1 - invalid",
    2310: "senderr/phone2 - invalid",
    2311: "senderr/document/type - field is missing or invalid",
    2312: "senderr/document/number - field is missing or invalid",
    2313: "senderr/document/country - field is missing or invalid",
    2314: "senderr/document/expirationdate - field is missing or invalid",
    2315: "senderr entity already in our database with different name, please send a copy of his ID to our customer service at customerservice@bemosenderrr.com.",
    2400: "recipient/firstname - field is missing or invalid",
    2401: "recipient/middlename - invalid",
    2402: "recipient/lastname - field is missing or invalid",
    2403: "recipient/address1 - invalid",
    2404: "recipient/address2 - invalid",
    2405: "recipient/city - invalid",
    2406: "recipient/state - invalid",
    2407: "recipient/zipcode - invalid",
    2408: "recipient/country - field is missing or invalid",
    2409: "recipient/phone1 - invalid",
    2410: "recipient/phone2 - invalid",
    2411: "recipient/document/type - field is missing or invalid",
    2412: "recipient/document/number - field is missing or invalid",
    2413: "recipient/document/country - field is missing or invalid",
    2414: "recipient/document/expirationdate - field is missing or invalid",
    2500: "account - field is missing or invalid",
    2501: "date - field is missing or invalid",
    2502: "account - not active",
    2503: "account - too many requested",
    2510: "date - field is missing or invalid",
    2600: "order not found",
    2601: "the order is paid",
    2602: "order canceled",
    2603: "the update cannot be performed",
    2604: "the order is in process, please retry later",
    2605: "the payment already requested by another payer",
    2606: "order blocked",
    2700: "agency/city - field is missing or invalid",
    2701: "agency/country - field is missing or invalid",
    2702: "agency/agencyId - field is missing or invalid",
    2703: "agency/agentName - field is missing or invalid",
}
