# Generated by Django 3.2.8 on 2022-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0002_apicollecttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmethod',
            name='icon_url',
            field=models.TextField(default=' ', verbose_name='URL of the icon for the frontend'),
        ),
    ]
