# Generated by Django 3.2.8 on 2022-02-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0003_transactionmethod_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmethod',
            name='icon_url',
        ),
    ]
