# Generated by Django 3.2.8 on 2022-02-23 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0004_remove_transactionmethod_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicollecttoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Expiration time of the token', null=True),
        ),
    ]
