# Generated by Django 3.2.8 on 2022-03-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0005_alter_apicollecttoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestMonitoring',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated UUID.', primary_key=True, serialize=False, unique=True, verbose_name='Internal UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically generated upon creation of the object.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated to the last modification timestamp.', verbose_name='Updated at')),
                ('_version', models.CharField(blank=True, help_text='Datatstore version used in mutations', max_length=255, null=True)),
                ('method', models.CharField(blank=True, help_text='The HTTP method of the request', max_length=255, null=True)),
                ('path', models.CharField(blank=True, help_text='The url after the base url of the domain', max_length=255, null=True)),
                ('body', models.JSONField(blank=True, help_text='The request body data', null=True)),
                ('request', models.JSONField(blank=True, help_text='The request params and headers', null=True)),
                ('response', models.JSONField(blank=True, help_text='The response, status and timestamp', null=True)),
                ('api_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
