# Generated by Django 3.2.8 on 2022-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0007_alter_globaltransaction_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+1234567890', max_length=255),
            preserve_default=False,
        ),
    ]
