# Generated by Django 3.2.8 on 2022-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0011_auto_20220317_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverificationrequest',
            name='partner_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Partner API response'),
        ),
        migrations.AlterField(
            model_name='kycverificationrequest',
            name='user_snapshot',
            field=models.JSONField(verbose_name='User data'),
        ),
        migrations.AlterField(
            model_name='userbankverificationrequest',
            name='partner_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Partner API response'),
        ),
        migrations.AlterField(
            model_name='userbankverificationrequest',
            name='user_snapshot',
            field=models.JSONField(verbose_name='User data'),
        ),
    ]
