# Generated by Django 3.2.8 on 2022-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0012_auto_20220317_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'Operation in progress'), ('CANCELLED', 'Operation cancelled'), ('FAILED', 'Operation failed'), ('COMPLETED', 'Operation succesful')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fundingtransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'Operation in progress'), ('CANCELLED', 'Operation cancelled'), ('FAILED', 'Operation failed'), ('COMPLETED', 'Operation succesful')], max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('FUNDING', 'Funding'), ('COLLECT', 'Collect'), ('KYC VERIFICATION', 'KYC Verification'), ('BANK VERIFICATION', 'Bank Verification'), ('CONVERSION', 'Conversion')], help_text='Partner type', max_length=30, verbose_name='Type'),
        ),
    ]
