# Generated by Django 3.2.8 on 2022-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0014_auto_20220328_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingtransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'Transaction in progress'), ('AUTH_ERROR', 'Authorization error'), ('COMPLETE_ERROR', 'Completion error'), ('ERROR', 'Transaction error'), ('SUCCESS', 'Transaction successful')], max_length=255),
        ),
        migrations.AlterField(
            model_name='globaltransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FUNDTRANSACTION_IN_PROGRESS', 'Fund transaction in progress'), ('COLLECTTRANSACTION_IN_PROGRESS', 'Collect transaction in progress'), ('REFUNDED', 'Transaction refunded'), ('REFUNDTRANSACTION_IN_PROGRESS', 'Refund transaction in progress'), ('SUCCESS', 'Transaction completed successfully'), ('CANCELLED', 'Transaction cancelled'), ('BLOCKED', 'Collect transactions blocked'), ('COLLECT_ERROR', 'Collect transaction error'), ('COLLECT_ON_HOLD', 'Collect transactions on hold'), ('FUNDING_ERROR', 'Funding transaction error'), ('NOT_FOUND', 'Transaction not found'), ('REFUNDED_ERROR', 'Refund Error')], default='NEW', help_text='Global Transaction status', max_length=64, verbose_name='Status'),
        ),
    ]
