# Generated by Django 3.2.8 on 2022-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0017_auto_20220426_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='config',
            field=models.JSONField(blank=True, help_text='Application Settings', null=True),
        ),
    ]
