# Generated by Django 3.2.8 on 2022-05-09 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0018_auto_20220426_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxLimitCumul',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated UUID.', primary_key=True, serialize=False, unique=True, verbose_name='Internal UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically generated upon creation of the object.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated to the last modification timestamp.', verbose_name='Updated at')),
                ('_version', models.CharField(blank=True, help_text='Datatstore version used in mutations', max_length=255, null=True)),
                ('cumulative_debut', models.DateTimeField(help_text='The date at which we started calculating cumulative limits')),
                ('operation', models.CharField(help_text='operation that triggered the new entry (send-money, refund or limit reset)', max_length=255)),
                ('amount', models.CharField(help_text='amount of the operation (send-money: positive; refund: negative)', max_length=255)),
                ('limit_1_month', models.CharField(help_text='The cumulative amount of all operations within the last 1 month', max_length=255)),
                ('last_1_month_refresh', models.DateTimeField(help_text='The date at which the last monthly reset was done')),
                ('limit_3_month', models.CharField(help_text='The cumulative amount of all operations within the last 3 month)', max_length=255)),
                ('last_3_month_refresh', models.DateTimeField(help_text='The date at which the last quarterly reset was done')),
                ('limit_12_month', models.CharField(help_text='The cumulative amount of all operations within the last 12 month', max_length=255)),
                ('last_12_month_refresh', models.DateTimeField(help_text='The date at which the last yearly reset was done')),
                ('total_transfered_amount', models.CharField(help_text='The total of all operations made since the beginning', max_length=255)),
                ('global_transaction', models.ForeignKey(blank=True, help_text='Global transaction associated to the operation (optional)', null=True, on_delete=django.db.models.deletion.RESTRICT, to='bemosenderrr.globaltransaction')),
                ('user', models.ForeignKey(help_text='The user that did the operation', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
