# Generated by Django 3.2.8 on 2022-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0019_auto_20220509_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='txlimitcumul',
            options={'ordering': ['created_at'], 'verbose_name': 'Transaction Limit Cumulative', 'verbose_name_plural': 'Transactions Limits Cumulatives'},
        ),
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
