# Generated by Django 3.2.8 on 2022-05-16 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0020_auto_20220516_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlerts',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated UUID.', primary_key=True, serialize=False, unique=True, verbose_name='Internal UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically generated upon creation of the object.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated to the last modification timestamp.', verbose_name='Updated at')),
                ('_version', models.CharField(blank=True, help_text='Datatstore version used in mutations', max_length=255, null=True)),
                ('can_get_receiver_sms', models.BooleanField(help_text='Can receive sms notifications')),
                ('can_receive_admin_alerts', models.BooleanField(help_text='Can receive email alerts? (new transactions and paid transactions alerts)')),
                ('user', models.ForeignKey(help_text='The statff or admin user', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
