# Generated by Django 3.2.8 on 2022-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0021_auto_20220516_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminalerts',
            options={'ordering': ['created_at'], 'verbose_name': 'Admin Alerts', 'verbose_name_plural': 'Admin Alerts'},
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, help_text='User preferred language', max_length=6, null=True),
        ),
    ]
