# Generated by Django 3.2.8 on 2022-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0024_auto_20220525_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminalerts',
            name='can_receive_celery_exceptions',
            field=models.BooleanField(default=False, help_text='Can receive celery email exceptions?'),
        ),
    ]
