# Generated by Django 3.2.8 on 2022-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0025_auto_20220525_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha_3_code',
            field=models.CharField(blank=True, help_text='3 letter country code', max_length=3, null=True, verbose_name='Country ISO Code alpha 3'),
        ),
    ]
