# Generated by Django 3.2.8 on 2022-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0026_auto_20220628_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(help_text='Country name', max_length=64, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_es',
            field=models.CharField(help_text='Country name', max_length=64, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(help_text='Country name', max_length=64, null=True, verbose_name='Country Name'),
        ),
    ]
