# Generated by Django 3.2.8 on 2022-07-13 15:50

from django.db import migrations, models
import django_cryptography.fields
import bemoSenderr.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0027_auto_20220629_1501'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=django_cryptography.fields.encrypt(bemoSenderr.models.user.JSONWrappedTextField(blank=True, default={}, null=True)),
        ),
        migrations.AlterField(
            model_name='collecttransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUCCESS', 'Transaction successfully collected'), ('AML_BLOCKED', 'Money laundering suspected !'), ('BLOCKED', 'Transaction blocked'), ('NOT_FOUND', 'Transaction not found'), ('CANCELLED', 'Transaction cancelled'), ('ERROR', 'Transaction error'), ('ON_HOLD', 'Transaction on hold'), ('IN_PROGRESS', 'Transaction in progress'), ('REJECTED', 'Transaction rejected '), ('COLLECT_READY', 'Transaction ready to be collected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fundingtransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'Transaction in progress'), ('AUTH_ERROR', 'Authorization error'), ('COMPLETE_ERROR', 'Completion error'), ('ERROR', 'Transaction error'), ('REFUNDED', 'Transaction refunded'), ('SUCCESS', 'Transaction successful')], max_length=255),
        ),
    ]
