# Generated by Django 3.2.8 on 2022-07-14 11:55

from django.db import migrations
import django_cryptography.fields
import bemosenderrr.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0028_auto_20220713_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credentials',
            field=django_cryptography.fields.encrypt(bemosenderrr.models.base.JSONWrappedTextField(blank=True, default=None, null=True)),
        ),
    ]
