# Generated by Django 3.2.8 on 2022-07-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0029_auto_20220714_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credentials',
        ),
    ]
