# Generated by Django 3.2.8 on 2022-07-14 13:10

from django.db import migrations
import django_cryptography.fields
import bemoSenderr.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0030_auto_20220714_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=django_cryptography.fields.encrypt(bemoSenderr.models.base.JSONWrappedTextField(blank=True, default=None, null=True)),
        ),
    ]
