# Generated by Django 3.2.8 on 2022-08-29 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0031_auto_20220714_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNetwork',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated UUID.', primary_key=True, serialize=False, unique=True, verbose_name='Internal UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically generated upon creation of the object.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated to the last modification timestamp.', verbose_name='Updated at')),
                ('_version', models.CharField(blank=True, help_text='Datatstore version used in mutations', max_length=255, null=True)),
                ('name', models.CharField(help_text='The mobile network name', max_length=255)),
                ('name_en', models.CharField(help_text='The mobile network name', max_length=255, null=True)),
                ('name_fr', models.CharField(help_text='The mobile network name', max_length=255, null=True)),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileNetworkAvailability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated UUID.', primary_key=True, serialize=False, unique=True, verbose_name='Internal UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically generated upon creation of the object.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated to the last modification timestamp.', verbose_name='Updated at')),
                ('_version', models.CharField(blank=True, help_text='Datatstore version used in mutations', max_length=255, null=True)),
                ('name', models.CharField(help_text='The mobile network name', max_length=255)),
                ('active', models.BooleanField(help_text='Mobile Network availbility')),
                ('country', models.ForeignKey(help_text='Destination country', on_delete=django.db.models.deletion.RESTRICT, to='bemosenderrr.country')),
                ('mobile_network', models.ForeignKey(help_text='The mobile network', on_delete=django.db.models.deletion.RESTRICT, to='bemosenderrr.mobilenetwork')),
            ],
            options={
                'verbose_name_plural': 'Mobile Networks Availabilities',
                'ordering': ['created_at'],
            },
        ),
    ]
