# Generated by Django 3.2.8 on 2022-08-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0033_auto_20220829_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenetwork',
            name='partner_api_code_mapping',
            field=models.JSONField(blank=True, help_text="the keys for this dictionary must come from the api_config['serviceClass'] in the partner model", null=True),
        )
    ]
