# Generated by Django 3.2.8 on 2022-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0034_auto_20220830_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilenetwork',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='mobilenetwork',
            old_name='name_en',
            new_name='display_name_en',
        ),
        migrations.RenameField(
            model_name='mobilenetwork',
            old_name='name_fr',
            new_name='display_name_fr',
        )
    ]
