# Generated by Django 3.2.8 on 2022-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0035_auto_20220830_1817'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, help_text='A quick description of this user', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='periodictasksentry',
            name='schedule',
            field=models.IntegerField(default=10, help_text='The schedule in seconds.'),
        )
    ]
