# Generated by Django 3.2.8 on 2022-10-06 12:55

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0036_auto_20220916_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingtransaction',
            name='refund_api_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Refund API response'),
        ),
        migrations.AddField(
            model_name='fundingtransaction',
            name='refund_reference_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Refund transaction number'),
        )
    ]
