# Generated by Django 3.2.8 on 2022-10-13 10:23

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0037_auto_20221006_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmethod',
            name='code_name',
            field=models.CharField(blank=True, help_text='Delivery method code name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionmethod',
            name='img_url',
            field=models.TextField(blank=True, help_text='Image url of the delivery method', null=True),
        )
    ]
