# Generated by Django 3.2.8 on 2022-10-13 10:26

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bemoSenderr', '0038_auto_20221013_1123'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='transactionmethod',
            name='name_en',
            field=models.CharField(help_text='Delivery method name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionmethod',
            name='name_fr',
            field=models.CharField(help_text='Delivery method name', max_length=255, null=True),
        )
    ]
