# Generated by Django 3.2.8 on 2022-10-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemosenderrr', '0040_auto_20221013_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmethod',
            name='img_url',
        ),
        migrations.AddField(
            model_name='transactionmethod',
            name='img_urls',
            field=models.JSONField(default=dict, help_text='Image urls of the delivery method'),
        ),
    ]
